const tags = [
  { value: 'art', label: 'art' },
  { value: 'photography', label: 'photography' },
  { value: 'travel', label: 'travel' },
  { value: 'blogging', label: 'blogging' },
  { value: 'postaday', label: 'postaday' },
  { value: 'life', label: 'life' },
  { value: 'long-reads', label: 'long-reads' },
  { value: 'memorial-day', label: 'memorial-day' },
  { value: 'books', label: 'books' },
  { value: 'entertainment', label: 'entertainment' },
  { value: 'food', label: 'food' },
  { value: 'humor', label: 'humor' },
  { value: 'technology', label: 'technology' },
  { value: 'nature', label: 'nature' },
  { value: 'family', label: 'family' },
  { value: 'crafts', label: 'crafts' },
  { value: 'party', label: 'party' },
]

const interests = [
  { value: 'Basketball', label: 'Basketball' },
  { value: 'Golf', label: 'Golf' },
  { value: 'Running', label: 'Running' },
  { value: 'Walking', label: 'Walking' },
  { value: 'Soccer', label: 'Soccer' },
  { value: 'Volleyball', label: 'Volleyball' },
  { value: 'Badminton', label: 'Badminton' },
  { value: 'Yoga', label: 'Yoga' },
  { value: 'Pilates', label: 'Pilates' },
  { value: 'Swimming', label: 'Swimming' },
  { value: 'Ice Skating', label: 'Ice Skating' },
  { value: 'Figure Skating', label: 'Figure Skating' },
  { value: 'Rugby', label: 'Rugby' },
  { value: 'Darts', label: 'Darts' },
  { value: 'Football', label: 'Football' },
  { value: 'Tai Chi', label: 'Tai Chi' },
  { value: 'Bowling', label: 'Bowling' },
  { value: 'Rock Climbing', label: 'Rock Climbing' },
  { value: 'Dancing', label: 'Dancing' },
  { value: 'Taekwondo', label: 'Taekwondo' },
  { value: 'Weightlifting', label: 'Weightlifting' },
  { value: 'Sky Diving', label: 'Sky Diving' },
  { value: 'Boxing', label: 'Boxing' },
  { value: 'Board Games', label: 'Board Games' },
  { value: 'Table Tennis', label: 'Table Tennis' },
  { value: 'Hiking', label: 'Hiking' },
  { value: 'Juggling', label: 'Juggling' },
  { value: 'Oil Painting', label: 'Oil Painting' },
  { value: 'Sculpture', label: 'Sculpture' },
  { value: 'Drawing', label: 'Drawing' },
  { value: 'Stained Glass', label: 'Stained Glass' },
  { value: 'Origami', label: 'Origami' },
  { value: 'Programming', label: 'Programming' },
  { value: 'Magic', label: 'Magic' },
  { value: 'Makeup Art', label: 'Makeup Art' },
  { value: 'Hair Styling', label: 'Hair Styling' },
  { value: 'Acting', label: 'Acting' },
  { value: 'Fashion Design', label: 'Fashion Design' },
  { value: 'Carving', label: 'Carving' },
  { value: 'Writing', label: 'Writing' },
  { value: 'Sudoku', label: 'Sudoku' },
  { value: 'Blogging', label: 'Blogging' },
  { value: 'Book Club', label: 'Book Club' },
  { value: 'Listening to Podcasts', label: 'Listening to Podcasts' },
  { value: 'Singing', label: 'Singing' },
  { value: 'Lego Sets', label: 'Lego Sets' },
  { value: 'Model Cars', label: 'Model Cars' },
  { value: 'Puzzles', label: 'Puzzles' },
  { value: 'Video Games', label: 'Video Games' },
  { value: 'Cocktails', label: 'Cocktails' },
  { value: 'BBQ', label: 'BBQ' },
  { value: 'Baking', label: 'Baking' },
  { value: 'Online Game', label: 'Online Game' },
  { value: 'Bingo', label: 'Bingo' },
  { value: 'Card Games', label: 'Card Games' },
  { value: 'Furniture Building', label: 'Furniture Building' },
  { value: 'Sightseeing', label: 'Sightseeing' },
  { value: 'Knitting', label: 'Knitting' },
  { value: 'Sketching', label: 'Sketching' },
  { value: 'Visiting Museums', label: 'Visiting Museums' },
  { value: 'Poetry', label: 'Poetry' },
  { value: 'Meditation', label: 'Meditation' },
]

const categoryOptions = [
  'Corporate',
  'Fundraising',
  'Conferences and Workshops',
  'Virtual',
  'Fandom',
  'Festivals and Fairs',
  'Food and Drink',
  'Networking',
  'Hackathons',
  'Sports and Tournaments',
]

export { tags, interests, categoryOptions }
